# Generated by Django 5.2.2 on 2025-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tg_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
