# Generated by Django 5.2.2 on 2025-06-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
