services:
  app-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${APP_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${APP_DB_NAME:-bank_oltp2}
    volumes:
      - app-db-volume:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - my-network

volumes:
  app-db-volume: