services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081
    ports:
      - 8081:8081
    depends_on: [zookeeper, kafka]
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-connect:
    image: debezium/connect:2.3
    hostname: kafka-connect
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: "kafka-connect-group"
      CONFIG_STORAGE_TOPIC: "_connect-configs"
      OFFSET_STORAGE_TOPIC: "_connect-offsets"
      STATUS_STORAGE_TOPIC: "_connect-statuses"
      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      REST_ADVERTISED_HOST_NAME: "kafka-connect"
      REST_PORT: "8083"
      PLUGIN_PATH: "/kafka/connect"
    volumes:
      - ../kafka-connect/connectors:/kafka/connect/connectors
      - ../kafka-connect/init-connectors.sh:/kafka/connect/init-connectors.sh
      - ../kafka-connect/config/connect-distributed.properties:/kafka/config/connect-distributed.properties
      - ../kafka-connect/config/connect-log4j.properties:/kafka/config/connect-log4j.properties
    command: >
      bash -c "
        /kafka/bin/connect-distributed.sh /kafka/config/connect-distributed.properties &
        sleep 30 &&
        chmod +x /kafka/connect/init-connectors.sh &&
        /kafka/connect/init-connectors.sh &&
        wait
      "
    networks:
      - my-network

  ksql-server:
    image: confluentinc/ksqldb-server:0.28.2
    hostname: ksql-server
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_CONNECT_URL: "http://kafka-connect:8083"
    networks:
      - my-network

  ksql-cli:
    image: confluentinc/ksqldb-cli:0.28.2
    container_name: ksql-cli
    depends_on:
      - ksql-server
    entrypoint: /bin/sh
    tty: true
    networks:
      - my-network

# ---
# Пример curl для создания коннектора Debezium PostgreSQL CDC (запустить после старта kafka-connect):
# curl -X POST http://localhost:8083/connectors -H 'Content-Type: application/json' -d '
# {
#   "name": "debezium-postgres-connector",
#   "config": {
#     "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
#     "database.hostname": "app-db",
#     "database.port": "5432",
#     "database.user": "debezium",
#     "database.password": "dbz",
#     "database.dbname": "bank_oltp2",
#     "database.server.name": "dbserver1",
#     "topic.prefix": "dbserver1",
#     "plugin.name": "pgoutput",
#     "slot.name": "debezium_slot",
#     "publication.name": "debezium_pub",
#     "table.include.list": "public.*",
#     "tombstones.on.delete": "false",
#     "key.converter": "org.apache.kafka.connect.json.JsonConverter",
#     "value.converter": "org.apache.kafka.connect.json.JsonConverter"
#   }
# }'
# ---